#---------------------- Timer Settings ----------------------#
#             Settings for your MUtils-Timer                 #
#------------------------------------------------------------#
#   Most of these settings are safely customizable ingame!   #
#      Only edit them if you know what you are doing         #
#------------------------------------------------------------#

language: "en_US"